sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - npm install bower
  - bower install
script:
  - xvfb-run npm test
